### GET request to example server
@host = 127.0.0.1:3000/BibentlyFunctions
@event_id = 4a761353-7eb4-4565-8491-7a4c6ee4404d

###  List all events
GET http://{{host}}
Authorization: Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJkb2NrZXItcHJvamVjdC1pZCIsImF1dGhfdGltZSI6MTc2NTkyMDYwMywiZW1haWwiOiJhZG1pbkBsb2NhbGhvc3QuY29tIiwiZXhwIjoxNzY1OTI0MjAzLCJpYXQiOjE3NjU5MjA2MDMsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9kb2NrZXItcHJvamVjdC1pZCIsInN1YiI6ImxvY2FsLWFkbWluLXVpZCIsInVzZXJfaWQiOiJsb2NhbC1hZG1pbi11aWQifQ.

### List events (GET)
GET http://localhost:5000/?city=Warsaw&min_price=10.50&sort_dir=asc&page_size=5

### Filter by date
GET http://localhost:8080/?start_date=2024-01-01T00:00:00Z


### Create a new event

POST https://{{host}}/
Content-Type: application/json

{
  "organizer_name": "John Doe",
  "name": "Rock Concert",
  "price": 11.50,
  "type": "concert"
}


### Get event by ID

GET https://{{host}}/
    ?id={{event_id}}


### Update event by ID
PUT https://{{host}}/
Content-Type: application/json

{
  "id": "{{event_id}}",
  "organizer_name": "Jane Smith",
  "name": "Jazz Festival",
  "price": 150.99,
  "type": "festival"
}

### Delete event by ID
DELETE https://{{host}}/
    ?id={{event_id}}