services:
  firebase-emulators:
    image: andreysenov/firebase-tools:latest
    ports:
      - "4000:4000" # Emulator UI
      - "8080:8080" # Firestore
      - "9099:9099" # Auth
    volumes:
      - .:/app # Matches the host directory to /app
    working_dir: /app
    # depends_on removed because firestore-rules-generator is gone
    command: sh -c "firebase emulators:start --project local-project-id --only firestore,auth"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9099" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - NODE_ENV=development

  bibently-functions:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - firebase-emulators
    environment:
      - PORT=3000
      - FUNCTION_TARGET=BibentlyFunctions
      - LOCAL_ONLY=false
      - CORS_ALLOWED_ORIGIN=*
      - GOOGLE_CLOUD_PROJECT=local-project-id
      - FIRESTORE_DATABASE_ID=bibently-store
      - APP_ENV=development
      - FIRESTORE_EMULATOR_HOST=firebase-emulators:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:9099
      - FIRESTORE_ADMIN_UID=admin_user_xyz_123_secret_id
    volumes:
      - .:/app