services:
  
  bibently.application:
    container_name: bibently.application
    image: bibently.application:latest
    depends_on:
      bibently.store:
        condition: service_healthy
    networks:
      - bibently.application-services
    ports:
      - "127.0.0.1:5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - SERILOG__MINIMUMLEVEL__DEFAULT=Warning
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - EventsRepository__CONNECTIONSTRING=mongodb://bibently_user:bibently_password@bibently.store:27017/bibently?authSource=bibently
      - EventsRepository__DatabaseName=bibently
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    build:
      context: ../
      dockerfile: Dockerfile
  
  bibently.store:
    container_name: bibently.store
    image: mongo:8.2.1
    command: --bind_ip_all
    ports:
      - "127.0.0.1:27017:27017"
    environment: # todo: move somewhere else
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - bibently.application-services
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  mongo_data:
    
networks:
  bibently.application-services:
